AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "module/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"

# restore pre 0.45 behaviour
Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/NumericPredicate:
  EnforcedStyle: comparison

Lint/NonLocalExitFromIterator:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FormatString:
  EnforcedStyle: percent

Style/SpecialGlobalVars:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/WordArray:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  EnforcedStyle: only_raise

Style/RescueModifier:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Alias:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

# @todo use safe_load but its a big change
Security/YAMLLoad:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Performance/StringReplacement:
  Enabled: false
