source ENV["GEM_SOURCE"] || "https://rubygems.org"

gem "json", "~> 2.1.0"
gem "systemu", "~> 2.6.4"
gem "rdoc"
gem "yarjuf", "~> 1.0"
gem "rspec", "~> 2.11.0"
gem "mocha", "~> 0.10.0"
gem "mcollective-test"
gem "rake", "< 11.0"
