source ENV["GEM_SOURCE"] || "https://rubygems.org"

gem "systemu", "~> 2.6.4"
gem "rdoc"
gem "yarjuf", "~> 1.0"
gem "rspec", "~> 2.99.0"
gem "mocha", "~> 0.12.2"
gem "mcollective-test"
gem "rake", "< 11.0"
gem "rubocop", "1.6.1"
