version: 2
jobs:
  rspec_and_rubocop:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - run:
          name: Set ruby version to 3.2.3
          command: |
            rvm install 3.2.3
            echo . $(rvm 3.2.3 do rvm env --path) >> $BASH_ENV
      - checkout
      - run: ruby --version
      - run: bundle install
      - run: bundle exec rake test

workflows:
  version: 2
  test:
    jobs:
      - rspec_and_rubocop
