version: 2.1

orbs:
  ruby: circleci/ruby@2.1.3

jobs:
  rspec_and_rubocop:
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - ruby/install:
          version: '3.2.3'
      - run: ruby --version
      - run: bundle install
      - run: bundle exec rake test

workflows:
  version: 2
  test:
    jobs:
      - rspec_and_rubocop
