version: 2
jobs:
  rspec_and_rubocop:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - rspec_and_rubocop
